#pragma once

#define CH32X035_ESIG_UNIID1    0x1FFFF7E8
#define CH32X035_ESIG_UNIID2    0x1FFFF7EC
#define CH32X035_ESIG_UNIID3    0x1FFFF7F0

#define WCH_USBCDC_MANUF_STR            "ch32fun"
#define WCH_USBCDC_PROD_STR             "USB CDC Serial"
#define WCH_USBCDC_INTERF_STR           "CDC-Serial"
#define WCH_USBCDC_SERIAL_PREFIX        "XF"

#define STR_LEN(s) (sizeof(s) - 1)

#define WCH_USBCDC_MANUF_LEN            STR_LEN(WCH_USBCDC_MANUF_STR)
#define WCH_USBCDC_PROD_LEN             STR_LEN(WCH_USBCDC_PROD_STR)
#define WCH_USBCDC_INTERF_LEN           STR_LEN(WCH_USBCDC_INTERF_STR)
#define WCH_USBCDC_SERIAL_PREFIX_LEN    STR_LEN(WCH_USBCDC_SERIAL_PREFIX)
#define WCH_USBCDC_UID_HEX_CHARS        24
#define WCH_USBCDC_SERIAL_LEN           (WCH_USBCDC_SERIAL_PREFIX_LEN + WCH_USBCDC_UID_HEX_CHARS)

#define WCH_USBCDC_VENDOR_ID        0x16C0
#define WCH_USBCDC_PRODUCT_ID       0x27DD
#define WCH_USBCDC_DEVICE_VERSION   0x0100
#define WCH_USBCDC_LANGUAGE         0x0409
#define WCH_USBCDC_MAX_POWER_mA     500

#ifndef WCH_USBCDC_DEFAULT_FIFO_SIZE
#define WCH_USBCDC_DEFAULT_FIFO_SIZE 128
#endif
